# Generated by Django 5.2.2 on 2025-06-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExtMovs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extratomovimentacao',
            options={'verbose_name': 'Extrato de Movimentação', 'verbose_name_plural': 'Extratos de Movimentação'},
        ),
        migrations.RemoveField(
            model_name='extratomovimentacao',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='extratomovimentacao',
            name='documento',
        ),
        migrations.AlterField(
            model_name='extratomovimentacao',
            name='codigo_produto',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='extratomovimentacao',
            name='descricao_produto',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='extratomovimentacao',
            name='movimentacao',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='extratomovimentacao',
            name='qtd_movimentada',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='extratomovimentacao',
            name='saldo_anterior',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='extratomovimentacao',
            name='saldo_atual',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterModelTable(
            name='extratomovimentacao',
            table='extrato_movimentacao',
        ),
    ]
