# Generated by Django 5.2.2 on 2025-06-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExtMovs', '0002_alter_extratomovimentacao_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extratomovimentacao',
            name='codigo_produto',
            field=models.IntegerField(),
        ),
    ]
